//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DiffRHelper.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DiffRHelperParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IDiffRHelperListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DiffRHelperParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage([NotNull] DiffRHelperParser.MessageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DiffRHelperParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage([NotNull] DiffRHelperParser.MessageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DiffRHelperParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] DiffRHelperParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DiffRHelperParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] DiffRHelperParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DiffRHelperParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] DiffRHelperParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DiffRHelperParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] DiffRHelperParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DiffRHelperParser.jsonObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonObj([NotNull] DiffRHelperParser.JsonObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DiffRHelperParser.jsonObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonObj([NotNull] DiffRHelperParser.JsonObjContext context);
}
