//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DiffRHelper.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class DiffRHelperLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, INT=5, ID=6, NUM=7, COMMA=8, DOT=9, WS=10;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "INT", "ID", "NUM", "COMMA", "DOT", "WS"
	};


	public DiffRHelperLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DiffRHelperLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'{'", "'}'", null, null, null, "','", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "INT", "ID", "NUM", "COMMA", "DOT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DiffRHelper.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DiffRHelperLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,10,54,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,4,4,31,8,4,
		11,4,12,4,32,1,5,1,5,5,5,37,8,5,10,5,12,5,40,9,5,1,6,1,6,1,7,1,7,1,8,1,
		8,1,9,4,9,49,8,9,11,9,12,9,50,1,9,1,9,0,0,10,1,1,3,2,5,3,7,4,9,5,11,6,
		13,7,15,8,17,9,19,10,1,0,4,1,0,48,57,3,0,65,90,95,95,97,122,4,0,48,57,
		65,90,95,95,97,122,3,0,9,10,12,13,32,32,56,0,1,1,0,0,0,0,3,1,0,0,0,0,5,
		1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,
		0,17,1,0,0,0,0,19,1,0,0,0,1,21,1,0,0,0,3,23,1,0,0,0,5,25,1,0,0,0,7,27,
		1,0,0,0,9,30,1,0,0,0,11,34,1,0,0,0,13,41,1,0,0,0,15,43,1,0,0,0,17,45,1,
		0,0,0,19,48,1,0,0,0,21,22,5,40,0,0,22,2,1,0,0,0,23,24,5,41,0,0,24,4,1,
		0,0,0,25,26,5,123,0,0,26,6,1,0,0,0,27,28,5,125,0,0,28,8,1,0,0,0,29,31,
		7,0,0,0,30,29,1,0,0,0,31,32,1,0,0,0,32,30,1,0,0,0,32,33,1,0,0,0,33,10,
		1,0,0,0,34,38,7,1,0,0,35,37,7,2,0,0,36,35,1,0,0,0,37,40,1,0,0,0,38,36,
		1,0,0,0,38,39,1,0,0,0,39,12,1,0,0,0,40,38,1,0,0,0,41,42,7,0,0,0,42,14,
		1,0,0,0,43,44,5,44,0,0,44,16,1,0,0,0,45,46,5,46,0,0,46,18,1,0,0,0,47,49,
		7,3,0,0,48,47,1,0,0,0,49,50,1,0,0,0,50,48,1,0,0,0,50,51,1,0,0,0,51,52,
		1,0,0,0,52,53,6,9,0,0,53,20,1,0,0,0,4,0,32,38,50,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
